src/backend/utils/adt/graph.c
src/include/catalog/pg_operator.h
src/include/catalog/pg_proc.h
src/include/utils/graph.h

It is preferable to use `.` to get a property value from the given
vertex. But it is hard to use `.` because the scanner treats `.` as a
character, not an operator, and indirection rule uses `.` for the same
purpose. So, we add it as a vertex -> operator first.
The vertex -> operator actually calls the function for jsonb -> operator
with a Jsonb in the vertex and a property key as arguments.

feat: Add -> operator which get property value from vertex

---

src/backend/nodes/copyfuncs.c
src/backend/nodes/equalfuncs.c
src/backend/nodes/outfuncs.c
src/backend/parser/gram.y
src/include/nodes/nodes.h
src/include/nodes/parsenodes.h

Now, the parser can parse Cypher's pattern. However, there are some
workarounds due to the behavior of the scanner. First, we cannot parse
a very simple relationship `--` because the scanner treats it as an
inline comment. So, current implementation only can support it through
`-[]-`. Also, right direction `->` and `|` which connects multiple
relationship type constraints are treated as an operator. So, we use
`Op` token in the rule instead, and if the parser detects a parsed
token other than `->` and `|`, then it reports a syntax error.

feat(cypher): Implement pattern grammar

---

src/backend/parser/parse_clause.c
src/backend/utils/adt/graph.c
src/include/catalog/pg_operator.h
src/include/catalog/pg_proc.h
src/include/catalog/pg_type.h
src/include/utils/graph.h

Overall implementation of edge type is very similar to vertex type.
We use `GraphEdge` as the struct name of edge type because `Edge` is
already taken.
Some notable modifications are:
* struct `VertexId` is added to point a unique vertex; (oid, vid) pair
* now, vertex type uses `VertexId` instead of label NameData and vid

feat: Add `edge` type for Cypher relationships

---

src/backend/parser/gram.y
src/backend/parser/parse_utilcmd.c

When create edge labels, they can inherit other edge labels.
CREATE ELABEL elabel_name [ INHERIT ( parent_name [, ...] ) ];
https://github.com/bitnine-oss/agens-graph/issues/6

feat: Enable inheritance of edge labels

---

src/backend/parser/parse_clause.c

Add predicates in WHERE clause to remove duplicate nodes and
relationships. All nodes that are bound to a variable or anonymous must
be unique. And all edges must be unique.

feat: Remove duplicate nodes and relationships from results

---

src/backend/parser/parse_clause.c

It uses `jsonb_contains()`(same as `@>` operator) to constrain resulting
vertices/edges.

feat: Add property map constraints feature

---

src/backend/nodes/copyfuncs.c
src/backend/nodes/equalfuncs.c
src/backend/nodes/outfuncs.c
src/backend/parser/gram.y
src/backend/parser/parse_graph.c

It is impossible to refer to field aliases in the SQL WHERE clause.
Therefore, wrap MATCH clause with an additional SELECT statement which
has the WHERE qualifications so that WHERE can refer to variables
in the result of MATCH clause.

feat: Support WHERE in MATCH clause

---

src/backend/nodes/copyfuncs.c
src/backend/nodes/equalfuncs.c
src/backend/nodes/outfuncs.c
src/backend/parser/gram.y
src/backend/parser/parse_graph.c
src/include/nodes/parsenodes.h

Wrap RETURN clause with an additional SELECT statement which has the
ORDER BY, SKIP, and LIMIT options so that such options can refer to
aliased variables.

feat: Support ORDER BY, SKIP, and LIMIT in RETURN clause

---

src/backend/parser/parse_clause.c
src/backend/parser/parse_graph.c

And remove `!resjunk` assertion of piped results because they might
have `resjunk` targets due to ORDER or aggreate functions.

fix: Generate GROUP BY if aggreates exist

---

src/backend/parser/parse_expr.c
src/backend/parser/parse_graph.c
src/include/parser/parse_utilcmd.h
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

If type of `var` in expression `(var).ind` is vertex/edge, transform it
to `(var).prop_map #> ARRAY[ind...]`.
`ind` is a series of following operations;
* `.key`
* `['key']`
* `[index]`
And also, it is possible to use this syntax on jsonb/json.

feat: Support syntax for vertex/edge property access

---

src/backend/parser/parse_utilcmd.c
src/backend/utils/adt/graph.c
src/include/catalog/pg_proc.h
src/include/catalog/pg_type.h
src/include/utils/graph.h
src/test/regress/expected/type_sanity.out

Use `oid.lid` format as `graphid` in/out strings

fix: Add start/end to `edge` out format

---

doc/Makefile

If Sphinx was not installed, skip making documentation with a warning
message. Now, `make clean` and `make world` work.

chore: Fix doc/Makefile failure if Sphinx was not installed

---

src/backend/executor/nodeModifyGraph.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/equalfuncs.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfuncs.c
src/backend/optimizer/plan/planner.c
src/backend/parser/gram.y
src/backend/parser/parse_expr.c
src/backend/parser/parse_graph.c
src/include/nodes/execnodes.h
src/include/nodes/graphnodes.h
src/include/nodes/nodes.h
src/include/nodes/parsenodes.h
src/interfaces/ecpg/preproc/check_rules.pl
src/interfaces/ecpg/preproc/parse.pl
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

You can make `jsonb` object in any expressions through the following
syntax; `{expr: expr, ...}`. This is just a syntactic sugar for
`jsonb_build_object(expr, expr, ...)`.
`jsonb` is aware of following types;
* `date`
* `timestamp`
* `timestamptz`
* ARRAY
* composite types
Although JSON supports array of mixed types, `expr` for an array in the
current implementation is restricted to the PostgreSQL's `ARRAY[...]`
expression.

feat: Implement JSON object expression

---

src/backend/executor/nodeModifyGraph.c
src/backend/parser/gram.y
src/backend/parser/parse_graph.c

You can write an expression as a property map using `=expr`.
For example, `(n:person =jsonb_build_object('name', 'someone'))` for
a node. The result of `=expr` must be `jsonb` type.

feat: Support an expression as a property map in the pattern element

---

src/backend/parser/parse_graph.c

Use `@>` operator instead of `jsonb_contains()` to take the power of
GIN index.

fix: Change property map constraints to use `@>` operator

---

src/backend/parser/parse_graph.c
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

example query: `EXPLAIN MATCH ()-[r]->() RETURN r;`

feat: Remove unnecessary JOINs for empty nodes

---

src/backend/commands/graphcmds.c
src/test/regress/expected/cypher_ddl.out
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_ddl.sql
src/test/regress/sql/cypher_dml.sql

Set `graph_path` to the newly create graph when CREATE GRAPH succeeds
and `graph_path` is NULL, and to NULL if the dropped graph is current
`graph_path` when DROP GRAPH succeeds.

feat: Set `graph_path` adaptively

---

src/include/catalog/pg_operator.h

`graphid` was already prepared to be used with merge/hash JOINs.
`oprcanmerge` and `oprcanhash` columns in `pg_operator` catalog was
just not properly updated.

fix: make `graphid` merge and hash joinable

---

src/backend/executor/execUtils.c
src/backend/executor/nodeIndexscan.c
src/backend/executor/nodeSeqscan.c
src/backend/parser/parse_graph.c
src/include/catalog/pg_operator.h
src/include/catalog/pg_opfamily.h
src/include/executor/executor.h
src/include/nodes/execnodes.h

When doing `SeqScan` and `IndexScan` for vertex lables, if the scan is
under JOIN operations, determine whether skip the scan or not using
`expr` in `graphid = expr` qualification condition.

feat: Skip unneccessary vertex label scan

---

src/backend/parser/parse_expr.c
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

Use `#>>` instead of `#>` to get a value in a `jsonb` type.
Because `#>` returns `text` type, users must do explicit typecast on
the resulting value if the user wants to deal it as a different type.

fix: Change implementation of `(vertex).path...` expression

---

src/backend/parser/analyze.c
src/backend/parser/gram.y
src/test/regress/expected/sql_restriction.out

* Cypher query must end with a RETURN or an update clause.
* DELETE/SET/REMOVE clauses cannot end with a RETURN clause.
* There must be one type of consecutive update clauses.

fix: Restrict Cypher grammar

---

src/backend/parser/parse_graph.c
src/backend/parser/parse_utilcmd.c
src/backend/utils/adt/array_userfuncs.c

To use index only scan on edges without `id` in composite indices of
them, use (tableoid, ctid) pair to ensure edge uniqueness.
This commit has also some bug fixes in `array_position()` family.
Discussion: https://postgr.es/m/CAE+byMupUURYiZ6bKYgMZb9pgV1CYAijJGqWj-90W=nS7uEOeA@mail.gmail.com

fix: Use (tableoid, ctid) instead of graphid to ensure edge uniqueness

---

src/backend/catalog/ag_label.c
src/backend/parser/parse_utilcmd.c
src/backend/utils/adt/graph.c
src/include/utils/graph.h

Change it from 2^64 - 1 to 2^48 - 1 because the size of local ID is now
6 bytes.

fix: Adjust `max_value` of sequence for local ID

---

src/backend/executor/nodeModifyGraph.c
src/include/nodes/execnodes.h

The materialized slots are allocated from `es_query_cxt` so they must be
cleared for each vertex/edge insertion.
Closes #145

fix: Manage materialized slots for vertex/edge insertion

---

src/backend/executor/nodeModifyGraph.c
src/include/nodes/execnodes.h

ModifyGraph now uses `resultRelations` instead of `es_result_relations`
to allow multiple ModifyGraph can be executed in the same plan.

fix: ModifyGraph uses its own variable for result relations

---

src/backend/parser/parse_graph.c

`adjustFutureVertices()` modifies the given list of future vertices by
deleting elements which will not be referenced. If all elements in the
list are deleted, the list itself is also pfree'd. So, there is a case
that `transformClauseImpl()` updates `p_future_vertices` using already
pfree'd `future_vertices`.
Closes #154

fix: Return the modified list in `adjustFutureVertices()`

---

.travis.yml
src/bin/initdb/initdb.c

pg_stat_statements, pg_statsinfo, pg_hint_plan, and postgresql-hll are
now disabled by default.

chore: Stop enabling some extensions by default

---

src/bin/agens/command.c
src/bin/initdb/initdb.c
src/bin/scripts/createdb.c
src/bin/scripts/createlang.c
src/bin/scripts/createuser.c
src/bin/scripts/dropdb.c
src/bin/scripts/droplang.c
src/bin/scripts/dropuser.c
src/bin/scripts/po/ko.po
src/bin/scripts/reindexdb.c
src/bin/scripts/vacuumdb.c

* Change "PostgreSQL" in help messages of `createdb`, `createlang`,
`createuser`, `dropdb`, `dropuser`, `reindexdb`, `vacuumdb` to
"AgensGraph"
* Remove "Report bugs to ..." in help messages of above tools,
`initdb`, and `droplang`.
* Print detailed version information when `agens` prints out greetings

chore: Match messages printed by CLIs with AgensGraph

---

src/backend/commands/dropcmds.c

If object_name is not exists, drop command should return notice message.

fix: DROP graph_object IF EXISTS object_name

---

src/backend/commands/graphcmds.c

`CREATE GRAPH IF NOT EXISTS` returns ERROR when the given graph name
already exists. It should not return error.
Closes #192

fix: ERROR when `CREATE GRAPH IF NOT EXISTS`

---

src/backend/parser/parse_cypher_expr.c

UNKNOWN constants `'"'` and `'\"'` are the same as JSON string `"\""`.

feat: Implement numeric, string, and boolean literal

---

src/backend/executor/execQual.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/equalfuncs.c
src/backend/nodes/nodeFuncs.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfuncs.c
src/backend/optimizer/util/clauses.c
src/backend/parser/gram.y
src/backend/parser/parse_cypher_expr.c
src/include/nodes/execnodes.h
src/include/nodes/nodes.h
src/include/nodes/parsenodes.h
src/include/nodes/primnodes.h

If all property values in a map literal are constant, the map literal
will be pre-evaluated to make it a single constant.
Here is an example of map literal.
```
{
i: 7,
n: 7.0,
s: '"Hello\nAgensGraph\"',
t: true,
f: false,
'0': null,
'\n': 'AS-IS',
o: {
v: 'bitnine',
o: {
v: 'bitnine'
}
}
}
```
And the following is the evaluated result. Properties that have null as
their value are omitted.
```
{
"f": false,
"i": 7,
"n": 7.0,
"o": {
"o": {
"v": "bitnine"
},
"v": "bitnine"
},
"s": "\"Hello\nAgensGraph\"",
"t": true,
"\\n": "AS-IS"
}
```

feat: Implement map literal

---

src/backend/parser/parse_cypher_expr.c
src/backend/utils/adt/cypher_ops.c
src/include/catalog/pg_cast.h
src/include/catalog/pg_proc.h
src/include/utils/cypher_ops.h

The implementation of comparison operators (=, <>, <, >, <=, >=) uses
existing `jsonb` comparison functions. This has pros and cons. It
allows optimizer to make use of indexes. And the implementation is
relatively easy. However, those functions return `bool` value. It means
if users want to use the value as a literal value, type conversion from
`boot` to `jsonb` is required. So, implicit type conversion between
`jsonb` and `bool` is introduced.
The implementation of boolean operators (OR, AND, NOT) also uses
existing boolean expression implementation. It has similar pros and
cons to that of comparison operators.

feat: Implement comparison and boolean operators

---

src/backend/executor/execQual.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/equalfuncs.c
src/backend/nodes/nodeFuncs.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfuncs.c
src/backend/optimizer/util/clauses.c
src/backend/parser/gram.y
src/backend/parser/parse_cypher_expr.c
src/include/nodes/execnodes.h
src/include/nodes/nodes.h
src/include/nodes/primnodes.h

* Accessing non-exisiting properties returns null.
* `o.null`, `o.'null'`, `o[null]`, `o[NULL]`, and `o['null']` are equal.
* `o.true`, `o.'true'`, `o[true]`, `o[TRUE]`, and `o['true']` are equal.
* Property access on null is null. (e.g. `null.p`)
* Number, map, and list are invalid for the key value.
Let's assume that there is a map `m` with `{p1: 0, 'p\n2': {p3: 1}}`.
Both `m.p1` and `m['p' + 1]` will return `0`.
`m.'p\n2'` will return `{p3: 1}`. However, `m['p\n2']` will return null.
This is because `'p\n2'` in the definition of `m` is equal to that in
`m.'p\n2'` (a string which has 4 characters) but is different from that
in `m['p\n2']` (a string which has 2 characters and a newline character
in the middle). The `.` operator takes an identifier and use it AS-IS.
On the other hand, the …

feat: Implement property access

---

src/backend/executor/execQual.c
src/test/regress/expected/cypher_expr.out
src/test/regress/sql/cypher_expr.sql

Inner variable overwrites outer variable and it produces unexpected
result.
`RETURN [x IN [[0], [1]] WHERE length([y IN x]) = 1 | [y IN x]];`
Above query should produce `[[0], [1]]` but `[null, null]`.

fix: Nested use of variables in list comprehension

---

src/backend/parser/parse_cypher_expr.c

Current implementation of `transformParamRef()` in Cypher expression
calls `to_jsonb()` over parameters to convert those parameters to
`jsonb` value.
PostgreSQL cannot decide which function to use for the conversion when
the type of a parameter is `UNKNOWNOID` because there are three
`to_jsonb()` functions. (One for `jsonb` and others for `vertex` and
`edge`.)
Now, `coerce_type()` is called instead of `to_jsonb()` only if the type
of the parameter is `UNKNOWNOID`. This call will change the type to
`JSONBOID`.
When binding the actual parameter value to the parameter, `jsonb_in()`
or `jsonb_recv()` will be called with the value.

fix: Handle parameters with `UNKNOWNOID` type

---

src/backend/utils/adt/graph.c
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

When printing out `_vertex`, `_edge`, and `graphpath`, there is an
`Assert()` for NULL values in them. This commit removes it and modifies
the output functions of them, so that they print out `NULL` for NULL
values.

feat: Print NULL values in `_vertex`, `_edge`, and `graphpath`

---

src/backend/catalog/ag_label.c

The length of namedata type is considered as 64 byte always.

fix: Remove valgrind warning

---

src/backend/parser/parse_graph.c

The label name is not properly quoted. If the label has some characters
that are not suitable for unquoted identifier, the parsing of the label
creation query fails.

fix: Create a label that does not exist while running CREATE clause

---

README.md

I added an installation step for RedHat Enterprise Linux 7 to the manual. I built Agensgraph successfully today on such a system, but it seems flex and bison must be installed, but this step was missing. This maybe even affects Centos,but I haven't tried yet.

Added installation step for RHEL

---

src/backend/executor/execExpr.c
src/backend/executor/execExprInterp.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/equalfuncs.c
src/backend/nodes/nodeFuncs.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfuncs.c
src/backend/optimizer/util/clauses.c
src/backend/parser/gram.y
src/backend/parser/parse_cypher_expr.c
src/backend/parser/parse_graph.c
src/backend/utils/adt/cypher_ops.c
src/backend/utils/adt/ruleutils.c
src/include/catalog/pg_cast.h
src/include/catalog/pg_proc.h
src/include/executor/execExpr.h
src/include/nodes/nodes.h
src/include/nodes/primnodes.h
src/include/parser/parse_cypher_expr.h
src/include/utils/cypher_ops.h
src/test/regress/expected/cypher_ddl.out
src/test/regress/expected/cypher_dml.out
src/test/regress/expected/cypher_expr.out
src/test/regress/expected/graphid.out
src/test/regress/serial_schedule
src/test/regress/sql/cypher_dml.sql
src/test/regress/sql/cypher_expr.sql
src/test/regress/sql/graphid.sql

* Change the implementation of constants
* Handle `UNKNOWNOID` constants properly (::jsonb and ::text)
* Handle parameters AS-IS
* Implement type casting
* Implement pre-evaluating `CypherTypeCast`
* Implement auto type casting on function call
* Implement auto type casting on operators
* `jsonb` to `graphid` -> `numeric` to `graphid`
* Change `EQUALS_TILDE` to `EQUAL_TILDE`
* Update comment about token precedence in gram.y

feat: Make all built-in functions usable

---

src/backend/parser/parse_cypher_expr.c
src/backend/parser/parse_graph.c
src/test/regress/expected/cypher_dml.out
src/test/regress/expected/cypher_expr.out
src/test/regress/expected/cypher_shortestpath2.out

It is possible to return values that are not `jsonb` type due to
46685631c056d324772bfa90b50db4981a62374c. Coerce those values to `jsonb`
type except `bool` because previous to the commit, `bool` type values
were returned AS-IS.

fix: Coerce type of return values to `jsonb`

---

src/backend/executor/execExprInterp.c
src/backend/utils/adt/cypher_ops.c

It does not end with `'\0'` but `ExecEvalCypherTypeCast()` does not
care this properly. For example, `RETURN ('1' + '2')::text;` returns a
result like `"12~\x7F@"`. And we can save 1 byte if a C-string is
stored in it. This is applied to `jsonb_add()`.

fix: Handle `JsonbValue.val.string.val` properly

---

src/backend/utils/adt/graph.c
src/include/catalog/pg_amop.h
src/include/catalog/pg_amproc.h
src/include/catalog/pg_opclass.h
src/include/catalog/pg_opfamily.h
src/include/catalog/pg_proc.h

This change adds the following entries to the catalog to make vertex
hashable.
* `vertex_hash` function (and C implementation of it)
* A `vertex_ops` operator family for hash
* A `vertex_ops` operator class for `vertex` type and `vertex_ops`
operator family
* The existing `vertex = vertex` operator as an access method operator
for `vertex_ops` operator family
* `vertex_hash` function as a support prodecure for `vertex_ops`
operator family
Run the following SQL statements as a superuser to update the existing
catalog.
```
CREATE FUNCTION pg_catalog.vertex_hash(pg_catalog.vertex)
RETURNS pg_catalog.int4
LANGUAGE internal
IMMUTABLE
STRICT
PARALLEL SAFE
AS 'vertex_hash';
CREATE OPERATOR FAMILY pg_catalog.vertex_ops USING hash;
CREATE OPERATOR CLASS pg_catalog.vertex_ops
DEFAULT FOR TYPE …
```

fix: Make `=` operator with vertices work for hash join

---

src/backend/parser/parse_cypher_expr.c
src/test/regress/expected/cypher_func.out
src/test/regress/sql/cypher_func.sql

Notation: log10() refers to log base 10, ln() refers to log base e,
the natural logarithm.
The issue -
* Postgres SQL uses log10() for the log() function.
* Cypher uses ln() for the log() function.
* Our current implementation has a mix of log10() and ln() for
Cypher queries using the log() function - based on type.
A decision was made to make our implementation of Cypher mirror the
standard. So, all Cypher log() function calls are to use ln() under
the hood.
To do this the following was changed -
* `parse_cypher_expr.c` was modified to transform all Cypher log()
function calls to ln(), the Postgres internal function for ln().
* `cypher_func.sql` had regression tests added for the above change.
* `cypher_func.out` had the correct regression test output added
for the above tests.
Note: …

fix: Make all Cypher log() calls use ln(), the natural logarithm

---

src/backend/executor/execExprInterp.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/equalfuncs.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfuncs.c
src/backend/optimizer/util/clauses.c
src/backend/parser/parse_cypher_expr.c
src/backend/parser/parse_shortestpath.c
src/backend/utils/adt/cypher_ops.c
src/include/catalog/pg_cast.h
src/include/catalog/pg_proc.h
src/include/nodes/primnodes.h
src/include/utils/cypher_ops.h
src/test/regress/expected/cypher_func.out
src/test/regress/expected/cypher_plpgsql.out
src/test/regress/expected/cypher_substring.out
src/test/regress/sql/cypher_func.sql
src/test/regress/sql/cypher_plpgsql.sql
src/test/regress/sql/cypher_substring.sql

This change removes jsonb type casts from pg_cast and adjusts the code
accordingly to provide those casts programmatically. See AG-245 for
more details.
In order to facilitate these changes, CoercionContext and TYPCATEGORY
fields are added to the CypherTypeCast structure. These additions
enable more granularity in the `ExecEvalCypherTypeCast` runtime
coercions.  This added granularity is needed to make the correct
casts at runtime.
The casts removed from pg_cast are as follows -
* Casts between JSONBOID and BOOLOID
* Casts from JSONBOID to INT4OID, INT8OID, FLOAT8OID, & NUMERICOID
These casts are programmatically added to -
* `coerce_expr` is rewritten to prioritize our JSONBOID casts over
those of postgres, to create the CypherTypeCast for our casts, and
to populate the CoercionContext …

fix: Remove jsonb type casts from pg_cast (AG-245)

---

src/backend/parser/parse_cypher_expr.c

This fix is to correct issue AG-255 "The Collect function...".
The issue is caused by our new `coerce_expr` function processing
ANY*OID (ex: ANYARRAYOID, ANYENUMOID, etc) output types and wrapping
them in a CypherTypeCast node.
Prior to AG-245, the `coerce_to_target_type` function processed the
ANY*OID output types and just returned the node.
This fix adds in checks for ANY*OID output types so that we avoid
processing them and leave them for `coerce_to_target_type`.
-jrg

fix: Improper type casting of ANY*OID (AG-255)

---

src/backend/executor/nodeShortestpath.c
src/include/nodes/execnodes.h

This fix is to correct issue AG-252 which is due to FieldSelect
expressions that are unexpected.
The original shortest path algorithm appears to have not anticipated the
cases where the source/target expressions might be something other than a
Param expression. To fix this issue, logic needed to be added to allow
FieldSelect expressions in source/target nodes.
The following is done to correct the issue -
The Hash2SideState structure had the following fields added to support
the fix.
* bool       isFieldSelect;  To flag a FieldSelect node.
* Param	    *correctedParam; To hold the corrected Param node.
* HeapTuple  vertexRow;      To hold the vertexRow for reuse;
* TupleDesc  tupleDesc;      To hold a tuple descriptor for reuse.
The support function `replace_vertexRow_graphid` is added to …

fix: Shorestpath crashed on FieldSelect exprs (AG-252)

---

src/backend/executor/nodeDijkstra.c
src/include/nodes/execnodes.h

This fix is to correct issue AG-260 which is due to FieldSelect
expressions that are unexpected in ExecDijkstra.
Please see commit d77f5bfc68e44c4136fa91e8db368cf8c40fdd09 for an
explaination of the issue. The fix is also similar, with the exception
of the need to only deal with the source node.
-jrg

fix: ExecDijkstra crashes on FieldSelect exprs (AG-260)

---

src/backend/executor/nodeNestloopVle.c
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

This fix is to correct issue AG-254 which is due to how Postgres
implements the LIMIT clause - basically, terminating a query in
progress once it receives the requested number of rows from it.
The `ExecEndNestLoopVLE` function, which deals with cleanup for the VLE
nested loop, was not cleaning up its internal context stack. This
caused, in some cases, the index routines to improperly free the
contexts, sometimes attempting to free them twice.
The fix is to properly unwind the context stack. The following was done
to correct the issue -
* `ExecEndNestLoopVLE` was modified to clean up the context
stack, if necessary, by calculating and checking its depth.
Additionally, regression tests were modified to include tests for this
fix -
* `regress/sql/cypher_dml.sql` - tests added.
* …

fix: LIMIT clause causes VLEs [*] to crash (AG-254)

---

src/backend/executor/nodeShortestpath.c
src/test/regress/expected/cypher_shortestpath.out
src/test/regress/sql/cypher_shortestpath.sql

previously `shortestpath` run without Parallel scan, but it now work with Parallel and the two results are returned differently depending on the situation.
and, another fix is free minimal tuples if needed.

test: (ShortestPath) Fix regression for shortestpath

---

src/backend/nodes/nodeFuncs.c
src/test/regress/expected/cypher_dml2.out
src/test/regress/parallel_schedule
src/test/regress/sql/cypher_dml2.sql

The argument of CypherTypeCast must be passed to "walker". but,
"expression_tree_walker" is called again and the "walker" cannot perform the
required tasks.
So, changed to call walker. If required, "expression_tree_walker" is called
back from "walker".
In addition, this corrects errors caused by Cypher not detecting the nested
aggregate function.

fix: Corrects CypherTypecast in expression_tree_walker().

---

src/backend/parser/parse_cypher_expr.c
src/backend/utils/adt/cypher_funcs.c
src/include/catalog/pg_proc.dat
src/include/utils/cypher_funcs.h
src/test/regress/expected/cypher_dml2.out
src/test/regress/sql/cypher_dml2.sql

AGV2-23 Implement `head()`, `last()`, `tail()` for array type. #525 
Previously, all data was cast as JSONB to process the value. however, `head()`,
`last()`, `tail()` function also casting values that should not be casting into
JSONB, resulting in unexpected results. so, implement a separate function for
the Array type.

AGV2-23 Implement head(), last(), tail() for array type. #525

---

src/tools/msvc/Mkvcbuild.pm
src/tools/msvc/Solution.pm

fix: Corrects windows build failure.
- (Windows) Corrects AG_VERSION, AG_COMP_VERSION, AG_GIT_REVISION definition.
- (Windows) Copy psql as agens, pg_ctl as ag_ctl.
**_Need to applied AG 2.5~2.13._**

AGV2-41 Corrects windows build failure.

---

src/backend/commands/dropcmds.c
src/bin/pg_dump/pg_dump.c

AgensGraph cannot drop non empty label(table) without CASCADE option. so, When
use pg_restore with --clean flag, uses CASCADE option on labels.

Fix error case for pg_restore (LABEL Restore).

---

src/bin/initdb/initdb.c

Fixed an error where the database was not created when initdb was used without the -D option.
And if you don't use the -D option, you need to add the AGDATA environment.

Fixed initdb error without -D options

---

src/backend/parser/analyze.c
src/test/regress/expected/cypher_dml.out
src/test/regress/expected/cypher_dml2.out
src/test/regress/expected/cypher_eager.out
src/test/regress/sql/cypher_dml2.sql

#589 
It seems to be a transaction issue related to the removed logic now, but it needs to be checked.
https://github.com/bitnine-oss/agensgraph/blob/ee9b2995a449c42393d638730e54356398a6f1b4/src/backend/executor/nodeNestloop.c#L174-L204

fix: remove cypher read clause restriction.

---

.github/workflows/regression.yml
src/backend/commands/graphcmds.c
src/backend/executor/execCypherDelete.c
src/backend/executor/execCypherMerge.c
src/backend/executor/execCypherSet.c
src/backend/nodes/nodeFuncs.c
src/backend/parser/parse_graph.c
src/backend/tcop/utility.c
src/backend/utils/adt/ruleutils.c

- Added fall through comments where expected to silence compiler warnings
- Added missing break statements in switch cases
- Fixed unused variable warnings
- Additionally, this PR removes silent flag from the regression test workflow to see the build logs

chore: Resolve warnings in the build

---

src/bin/psql/tab-complete.c

Tab complete is added for `CREATE/DROP` Graph, VLable and ELable
Psql meta command support to list graphs, labels and index `\dG, \dGv, \dGe \dGV`

Implement tab completion for Graph CREATE,DROP and psql meta command

---

src/bin/pg_dump/pg_dump.c

This commit fixes a binary upgrade issue.
After the upgrade, a graph element could not be created with an old label that existed before the upgrade or dump.
- regression test
- passed
- pg_upgrade test 
-  worked after this commit
- dump/restore test
-  worked after this commit

[v2.16] fix upgrade issue

---

src/bin/psql/tab-complete.c

1. Add some psql tab-completion entries for convenience.
2. Caveat: Not all Cypher syntax is supported.

Add: Tab-completion for AgensGraph syntax
