src/backend/parser/parse_clause.c

It supports;
* multiple patterns with pattern chains
* variables
* label constraints and type constraints
It does not support;
* variables from previous clauses
* ORed types constraints (e.g. `-[:type1|type2]-`)
* property constraints (e.g. `({key: value})`, `-[{key: value}]-`)
* WHERE clause

feat(cypher): Implement basic MATCH pattern processing

---

src/backend/parser/parse_clause.c

Current logic doesn't work correctly with the pattern
`MATCH (a)-[]-(b), (c)-[]-(d), (b)-[]-(c) RETURN ...`.
Fix it to get `(a)-[]-(b), (c)-[]-(d), (b)-[]-(c)` instead of
`(a)-[]-(b), (b)-[]-(c)` and `(c)-[]-(d)`.

fix: Fix the logic for connected components

---

src/backend/parser/parse_clause.c
src/backend/utils/adt/graph.c
src/include/catalog/pg_proc.h
src/include/utils/graph.h

fix: Add `eid` to edge type

---

doc/source/ddl.rst
src/backend/parser/parse_utilcmd.c

This is the draft of ddl.rst. 
I have lost my first draft of ddl.rst while I tried to resolve my git merge trouble. So I write it again.
Please review the sentences and document format.
Thank you.

Draft of the Agens DDL manual

---

src/backend/parser/parse_graph.c
src/backend/parser/parse_utilcmd.c
src/backend/utils/adt/graph.c
src/bin/initdb/initdb.c
src/include/catalog/pg_attribute.h
src/include/catalog/pg_class.h
src/include/catalog/pg_operator.h
src/include/catalog/pg_proc.h
src/include/catalog/pg_type.h
src/include/parser/parse_utilcmd.h
src/include/utils/graph.h

* make vertex/edge type composite types instead of base types
* change some names;
vid/eid, inOID, incoiming, outOID, outgoing, properties
-> id, start_oid, start_id, end_oid, end_id, prop_map
* refactor parse_graph.c

feat: make vertex/edge type composite types

---

src/backend/nodes/copyfuncs.c
src/backend/nodes/equalfuncs.c
src/backend/nodes/outfuncs.c
src/backend/parser/analyze.c
src/backend/parser/gram.y
src/backend/parser/parse_graph.c
src/include/nodes/nodes.h
src/include/nodes/parsenodes.h
src/include/parser/parse_graph.h

* WITH clause is the same as RETURN clause with WHERE
* current grammar does not allow WITH clause to be the first clause due
to conflicts with WITH in SQL

feat: Support WITH clause

---

src/backend/nodes/equalfuncs.c
src/backend/parser/parse_clause.c
src/backend/parser/parse_graph.c
src/include/parser/parse_clause.h

Generate GROUP BY from target list automatically. If a variable is not
within the arguments of aggregate functions, add it to the GROUP BY.

feat: Support aggregates

---

src/backend/executor/Makefile
src/backend/executor/execMain.c
src/backend/executor/execProcnode.c
src/backend/executor/nodeCypherCreate.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/equalfuncs.c
src/backend/nodes/outfuncs.c
src/backend/optimizer/path/allpaths.c
src/backend/optimizer/plan/createplan.c
src/backend/optimizer/plan/planner.c
src/backend/optimizer/plan/setrefs.c
src/backend/optimizer/plan/subselect.c
src/backend/optimizer/prep/prepjointree.c
src/backend/parser/analyze.c
src/backend/parser/gram.y
src/backend/parser/parse_clause.c
src/backend/parser/parse_graph.c
src/backend/tcop/postgres.c
src/backend/tcop/pquery.c
src/include/executor/nodeCypherCreate.h
src/include/nodes/execnodes.h
src/include/nodes/nodes.h
src/include/nodes/parsenodes.h
src/include/nodes/plannodes.h
src/include/optimizer/planmain.h
src/include/parser/parse_graph.h

Do not collaborate with other clause,
just simply create a given graph pattern.

feat: implement create clause

---

README.md
config.sh

config.sh runs configure script with default options
for stored procedures, encriytion, authentification and extensions.

chore: Add config.sh for buiding Agens Graph with default options

---

src/test/regress/expected/cypher_ddl.out
src/test/regress/expected/cypher_dml.out
src/test/regress/expected/errors.out
src/test/regress/expected/plpgsql.out
src/test/regress/expected/sanity_check.out
src/test/regress/expected/type_sanity.out
src/test/regress/output/misc.source
src/test/regress/parallel_schedule
src/test/regress/serial_schedule
src/test/regress/sql/cypher_ddl.sql
src/test/regress/sql/cypher_dml.sql
src/test/regress/sql/plpgsql.sql

* add cypher dml test
* add cypher ddl test

feat: Add regression test for cypher query

---

src/backend/parser/parse_utilcmd.c

The default value of the `prop_map` column in vertex and edge labels
is now `jsonb_build_object()`(empty JSON object).

fix: Add DEFAULT constraint to `prop_map` in vertex and edge

---

src/backend/parser/parse_expr.c
src/backend/utils/adt/graph.c
src/include/catalog/pg_cast.h
src/include/catalog/pg_proc.h
src/include/catalog/pg_type.h
src/include/utils/graph.h

* `label()` (also `labels()` and `type()`)
* `length()`
* `vertices()` and `edges()` (also `nodes()` and `relationships()`)
* `start_vertex()` and `end_vertex()`
(also `startnode()` and `endnode()`)

feat: Support various functions for vertex/edge/graphpath

---

src/backend/utils/adt/graph.c
src/include/catalog/pg_proc.h

* `label()` and `type()`: cstring -> text
* `labels()`: _cstring -> _text

fix: Change return type of the functions which returns label(s)

---

src/backend/parser/parse_expr.c
src/backend/parser/parse_graph.c
src/backend/parser/parse_relation.c
src/include/parser/parse_node.h
src/include/parser/parse_relation.h
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

The sytnax was `(var).ind`. Change it to `var.ind`.

fix: Change syntax for vertex/edge property access

---

src/backend/executor/nodeModifyGraph.c

Current implementation uses per query memory context.

fix: Use per tuple memory context when executing `CREATE`

---

.travis.yml
LICENSE
README.md

Add license file for the Agens Graph

Chore: Add LICENSE file

---

src/bin/psql/help.c

chore: Add usage for \dG[elv]

---

src/backend/utils/misc/guc.c
src/bin/initdb/initdb.c
src/bin/pg_controldata/pg_controldata.c
src/bin/pg_ctl/pg_ctl.c
src/bin/pg_xlogdump/pg_xlogdump.c
src/test/regress/pg_regress.c

* Can set location for a default database cluster.

chore: add environment variable AGDATA

---

src/backend/parser/gram.y
src/backend/parser/parse_graph.c
src/include/parser/parse_node.h
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

And clean up gram.y and regression tests.

fix: Use LATERAL JOIN when transforming OPTIONAL MATCH

---

src/include/catalog/ag_label.h

Present Natts_ag_label is 4.
But it should be 5 because of appending Anum_ag_label_labid.

fix: The definition of Natts_ag_label should be changed.

---

.travis.yml

Currently, travis seems to have a problem.([link](https://github.com/travis-ci/travis-ci/issues/6861)).
Until the problem is solved, use the 'sudo' option as a workaround, temporarily.

Chore: fixed travis settings

---

README.md

Add the documentation link and change the product name.

Modification of README.md

---

src/backend/parser/parse_graph.c

Given a property constraint like `{name: {first: 'Tom'}, age: 30}`,
it will be transformed to as below.
```
WHERE properties #>> '{name,first}'::text[] AND
properties #>> '{age}'::text[]
```
And if one of the target label and its sub-labels has a GIN index on
the `properties` column, it will add the following qualification.
`properties @> jsonb_build_object(...)`

feat: Make use of property index for property constraints

---

src/backend/executor/nodeModifyGraph.c
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

fix: Possible to CREATE with invalid expression

---

src/backend/commands/operatorcmds.c
src/backend/parser/gram.y
src/backend/parser/parse_expr.c
src/backend/parser/parse_target.c
src/backend/parser/scan.l
src/backend/utils/misc/guc.c
src/include/parser/parser.h
src/pl/plpgsql/src/pl_funcs.c
src/pl/plpgsql/src/pl_gram.y
src/test/regress/case_sensitive_ident.diff

Add `case_sensitive_ident` and `case_compat_type_func` GUC variables
to support case-sensitive identifier.
This pull request is for #205.

Support case-sensitive identifier

---

src/backend/parser/parse_graph.c

If a label which does not exist is used in CREATE or MERGE clauses,
the label will be created on demand.
Closes #204

feat: Create labels on demand in a query

---

src/backend/parser/gram.y
src/backend/parser/parse_cypher_expr.c
src/backend/utils/adt/Makefile
src/backend/utils/adt/cypher_ops.c
src/include/catalog/pg_operator.h
src/include/catalog/pg_proc.h
src/include/utils/cypher_ops.h
src/test/regress/expected/opr_sanity.out

Following arithmetic operators are implemented.
* `number + number`
* `number - number`
* `number * number`
* `number / number`
* `number % number`
* `number ^ number`
* `+number`
* `-number`
And string concatenation operator `+` is implemented.
* `string + string`
* `string + number`
* `number + string`

feat: Implement arithmetic operators and string concatenation

---

src/backend/executor/execQual.c
src/backend/nodes/nodeFuncs.c
src/backend/optimizer/util/clauses.c
src/backend/parser/parse_cypher_expr.c
src/include/nodes/execnodes.h
src/include/nodes/primnodes.h

* Add missing `break` statement
* Change the type of TRUE/FALSE from jsonb to bool
* Omit all properties that have null values when evaluating constant expressions
* Write some comments for the implementation

Enhance current Cypher expression imlementation

---

src/backend/executor/execQual.c
src/backend/executor/execUtils.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/equalfuncs.c
src/backend/nodes/nodeFuncs.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfuncs.c
src/backend/optimizer/util/clauses.c
src/backend/parser/gram.y
src/backend/parser/parse_cypher_expr.c
src/backend/utils/adt/ruleutils.c
src/include/nodes/execnodes.h
src/include/nodes/nodes.h
src/include/nodes/parsenodes.h
src/include/nodes/primnodes.h
src/include/parser/parse_node.h
src/test/regress/expected/cypher_dml.out

Author: Junseok Yang, Dehowe Feng

feat: Implement list comprehension

---

src/backend/parser/parse_cypher_expr.c
src/test/regress/expected/cypher_plpgsql.out
src/test/regress/parallel_schedule
src/test/regress/serial_schedule
src/test/regress/sql/cypher_plpgsql.sql

improve using parameter of pl/pgsql function on cypher
* able to use parameter of pl/pgsql function on cypher
* able to use variable declared in pl/pgsql block on cypher.

improve using parameter of pl/pgsql function on cypher

---

src/backend/executor/nodeModifyGraph.c

- fixed memory leak in CREATE and MERGE clauses.

fix: Memory leak occurs in ModifyGraph

---

src/backend/parser/parse_graph.c
src/test/regress/expected/cypher_dml.out

- Eliminate features that merge expression modifications to the same element

fix: Memory leak occurs when SET is executed multiple times

---

src/backend/parser/parse_graph.c
src/test/regress/expected/cypher_dml.out

- Eliminate features that merge expression modifications to the same element

fix: Memory leak occurs when execute SET is executed multiple times

---

src/backend/access/transam/xact.c
src/backend/executor/nodeModifyGraph.c
src/backend/postmaster/pgstat.c
src/backend/utils/adt/Makefile
src/backend/utils/adt/graphmeta.c
src/backend/utils/misc/guc.c
src/include/catalog/ag_graphmeta.h
src/include/catalog/pg_proc.h
src/include/pgstat.h
src/include/utils/graph.h
src/test/regress/expected/graphmeta.out
src/test/regress/sql/graphmeta.sql

* Add a GUC on graphmeta which decide it works automatic or not.
* Add a function regather_meta() which reset and gather graphmeta.

feat: Improve Graph meta

---

configure
configure.in
src/backend/utils/adt/version.c
src/backend/utils/misc/guc.c
src/bin/pg_dump/pg_backup.h
src/bin/pg_dump/pg_backup_db.c
src/bin/pg_dump/pg_dump.c
src/bin/pg_upgrade/test.sh
src/include/catalog/pg_proc.h
src/include/pg_config.h.win32
src/interfaces/libpq/exports.txt
src/interfaces/libpq/fe-connect.c
src/interfaces/libpq/fe-exec.c
src/interfaces/libpq/libpq-fe.h
src/interfaces/libpq/libpq-int.h

* set AG_VERSION to 2.2devel
* GUC agversion is added
* Function agversion() is added

fix: Check agversion before dump graphmeta

---

src/backend/catalog/ag_label.c
src/backend/commands/trigger.c
src/backend/executor/execCypherCreate.c
src/backend/executor/execCypherDelete.c
src/backend/executor/execCypherMerge.c
src/backend/executor/execCypherSet.c
src/backend/executor/execMain.c
src/backend/executor/nodeModifyGraph.c
src/backend/parser/parse_graph.c
src/backend/postmaster/pgstat.c
src/include/catalog/ag_label_fn.h
src/include/executor/execCypherDelete.h
src/include/executor/execCypherSet.h
src/include/executor/nodeModifyGraph.h
src/include/nodes/execnodes.h
src/include/pgstat.h
src/include/utils/graph.h
src/test/regress/expected/cypher_dml2.out
src/test/regress/expected/sql_restriction.out
src/test/regress/sql/cypher_dml2.sql
src/tools/pgindent/typedefs.list

Implement Trigger for Cypher clauses. This is the same behavior as the
PostgreSQL trigger actions. This is an experimental function.

feat: Supports trigger (AGV2-52)

---

src/backend/executor/spi.c
src/include/executor/spi.h
src/pl/plpgsql/src/pl_exec.c
src/test/regress/expected/cypher_plpgsql.out
src/test/regress/sql/cypher_plpgsql.sql

GraphWriteClause may malfunction as it relates to the visibility of nodeModifyGraph. However, in order to collect bug reports and grant these choices to users, fixed that to allow.
Original PR : https://github.com/bitnine-oss/agensgraph/pull/449

fix: Allow CypherWriteClause on PL/PgSQL. (AGV2-59)

---

configure.in

Converted Version Info From 2.13_rc-0 to 2.13.0

[Mod] Converted Version Info

---

configure
configure.ac

Update copyright year to 2024 in configure and configure.ac

Update copyright year to 2024 in configure and configure.ac

---

README.md

Add header image with current release, issue, forks and star badges

Improved README with badges

---

README.md

Add header image with current release, issue, forks and star badges

[2.14] Improved README with badges

---

README.md

Add header image with current release, issue, forks and star badges

[2.15] Improved README with badges

---

src/backend/utils/activity/pgstat.c

[v2.15] fix: ensure agStatContext is deleted and reset

---

src/backend/utils/activity/pgstat.c

fix: ensure agStatContext is deleted and reset

---

src/backend/parser/gram.y
src/test/regress/expected/cypher_ddl.out
src/test/regress/sql/cypher_ddl.sql

fix: allow CREATE TABLE AS to be used with cypher

---

src/backend/parser/parse_cypher_utils.c
src/backend/parser/parse_graph.c
src/include/parser/parse_node.h
src/test/regress/expected/cypher_dml.out
src/test/regress/expected/cypher_plpgsql.out
src/test/regress/sql/cypher_dml.sql

fix: return null for non-existent labels in MATCH

---

src/backend/parser/gram.y
src/backend/parser/parse_graph.c
src/include/parser/parse_graph.h
src/test/regress/expected/cypher_dml.out
src/test/regress/expected/cypher_expr.out
src/test/regress/sql/cypher_expr.sql

fix: _ as variable name causes conflict

---

src/backend/parser/parse_cypher_expr.c
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

fix: unrecognized node type: 121

---

src/backend/parser/gram.y
src/test/regress/expected/cypher_ddl.out
src/test/regress/sql/cypher_ddl.sql

[v2.15] fix: allow CREATE TABLE AS to be used with cypher

---

src/backend/parser/parse_cypher_utils.c
src/backend/parser/parse_graph.c
src/include/parser/parse_node.h
src/test/regress/expected/cypher_dml.out
src/test/regress/expected/cypher_plpgsql.out
src/test/regress/sql/cypher_dml.sql

[v2.15] fix: return null for non-existent labels in MATCH

---

src/backend/parser/gram.y
src/backend/parser/parse_graph.c
src/include/parser/parse_graph.h
src/test/regress/expected/cypher_dml.out
src/test/regress/expected/cypher_expr.out
src/test/regress/sql/cypher_expr.sql

[v2.15] fix: _ as variable name causes conflict

---

src/backend/parser/parse_cypher_expr.c
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

[v2.15] fix: unrecognized node type: 121

---

src/backend/parser/parse_cypher_expr.c
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

[v2.14] fix: unrecognized node type: 121

---

src/backend/parser/parse_cte.c
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

fix: server crash on using CTE with cypher

---

src/backend/parser/gram.y
src/backend/parser/parse_graph.c
src/include/parser/parse_graph.h
src/test/regress/expected/cypher_dml.out
src/test/regress/expected/cypher_expr.out
src/test/regress/sql/cypher_expr.sql

[v2.13] fix: _ as variable name causes conflict

---

src/backend/parser/gram.y
src/backend/parser/parse_graph.c
src/include/parser/parse_graph.h
src/test/regress/expected/cypher_dml.out
src/test/regress/expected/cypher_expr.out
src/test/regress/sql/cypher_expr.sql

[v2.14] fix: _ as variable name causes conflict

---

src/backend/parser/parse_cypher_expr.c
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

[v2.13] fix: unrecognized node type: 121

---

src/backend/parser/parse_graph.c
src/include/parser/parse_node.h
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

[v2.15] fix: variable reuse across clauses

---

src/backend/parser/parse_cte.c
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

[v2.15] fix: server crash on using CTE with cypher

---

src/backend/parser/parse_graph.c
src/include/parser/parse_node.h
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

[v2.14] fix: variable reuse across clauses

---

src/backend/parser/parse_graph.c
src/include/parser/parse_node.h
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

[v2.13] fix: variable reuse across clauses

---

README.md

Add quickstart guide with docker in README

---

README.md

[v2.15] chore: Add quickstart with docker section in README

---

src/pl/plpgsql/src/pl_exec.c
src/test/regress/expected/cypher_ddl.out
src/test/regress/sql/cypher_ddl.sql

fix: Row count in get diagnostics

---

src/backend/executor/execCypherDelete.c
src/backend/executor/nodeModifyGraph.c
src/test/regress/expected/cypher_privileges.out
src/test/regress/sql/cypher_privileges.sql

This PR is for the fixing issue #516 and also update missing point of #624
And reverting changes of the commit 7e2394c9b77da5024c4117459a5f98cb95187a86 and f12f98fec47693d53ed0315c97d946b2d68d51fa
More details are in the commit message below.
The regression checks has been passed.
The clang, gcc compilation has been passed.

Fix: ACL logic to the ModifyGraph

---

src/backend/executor/execCypherDelete.c
src/backend/executor/nodeModifyGraph.c
src/test/regress/expected/cypher_privileges.out
src/test/regress/sql/cypher_privileges.sql

This PR is for the v2.16, contents are same with PR #737 
Regression test is passed.

[v2.16] Fix: ACL logic to the ModifyGraph

---

src/bin/pg_dump/pg_dump.c

See PR #750
- regression test
- passed
- pg_upgrade test
- worked after this commit
- dump/restore test
- worked after this commit

[V2.15] fix upgrade issue

---

src/bin/pg_dump/pg_dump.c

See PR #750
- regression test
- passed
- pg_upgrade test
- worked after this commit
- dump/restore test
- worked after this commit

fix upgrade issue

---

doc/src/sgml/ref/allfiles.sgml
doc/src/sgml/ref/cypher_alter_elabel.sgml
doc/src/sgml/ref/cypher_alter_vlabel.sgml
doc/src/sgml/ref/cypher_create.sgml
doc/src/sgml/ref/cypher_create_constraint.sgml
doc/src/sgml/ref/cypher_create_elabel.sgml
doc/src/sgml/ref/cypher_create_graph.sgml
doc/src/sgml/ref/cypher_create_property_index.sgml
doc/src/sgml/ref/cypher_create_vlabel.sgml
doc/src/sgml/ref/cypher_drop_constraint.sgml
doc/src/sgml/ref/cypher_drop_elabel.sgml
doc/src/sgml/ref/cypher_drop_graph.sgml
doc/src/sgml/ref/cypher_drop_property_index.sgml
doc/src/sgml/ref/cypher_drop_vlabel.sgml
doc/src/sgml/ref/cypher_load_from.sgml
doc/src/sgml/ref/cypher_match.sgml
doc/src/sgml/ref/cypher_merge.sgml
doc/src/sgml/ref/cypher_path.sgml
doc/src/sgml/ref/cypher_remove.sgml
doc/src/sgml/ref/cypher_skip.sgml
doc/src/sgml/ref/cypher_unwind.sgml
doc/src/sgml/reference.sgml

Initial sgml contents for the agensgraph command.
Contents are under the `VI. Reference`,  newly added `II. Cypher Commands` and `III. Cypher Syntax`.

Add: initial sgml documentation for agensgraph syntax

---

doc/src/sgml/ref/allfiles.sgml
doc/src/sgml/ref/cypher_alter_elabel.sgml
doc/src/sgml/ref/cypher_alter_vlabel.sgml
doc/src/sgml/ref/cypher_create.sgml
doc/src/sgml/ref/cypher_create_constraint.sgml
doc/src/sgml/ref/cypher_create_elabel.sgml
doc/src/sgml/ref/cypher_create_graph.sgml
doc/src/sgml/ref/cypher_create_property_index.sgml
doc/src/sgml/ref/cypher_create_vlabel.sgml
doc/src/sgml/ref/cypher_drop_constraint.sgml
doc/src/sgml/ref/cypher_drop_elabel.sgml
doc/src/sgml/ref/cypher_drop_graph.sgml
doc/src/sgml/ref/cypher_drop_property_index.sgml
doc/src/sgml/ref/cypher_drop_vlabel.sgml
doc/src/sgml/ref/cypher_load_from.sgml
doc/src/sgml/ref/cypher_match.sgml
doc/src/sgml/ref/cypher_merge.sgml
doc/src/sgml/ref/cypher_path.sgml
doc/src/sgml/ref/cypher_remove.sgml
doc/src/sgml/ref/cypher_skip.sgml
doc/src/sgml/ref/cypher_unwind.sgml
doc/src/sgml/reference.sgml

[V2.16] Add: initial sgml documentation for agensgraph syntax

---

src/backend/commands/graphcmds.c
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

It's same PR with #756 
Regression test checked

[v2.16] Fix: Invalid label numbering after RENAME command

---

src/backend/commands/graphcmds.c
src/test/regress/expected/cypher_dml.out
src/test/regress/sql/cypher_dml.sql

[v2.15] Fix: Invalid label numbering after RENAME command

---

src/bin/pg_dump/pg_dump.c

[v2.14] fix upgrade issue

---

src/bin/psql/tab-complete.c

It's same with #763, For the v2.16

[v2.16] Add: Tab-completion for AgensGraph syntax

---

src/bin/psql/tab-complete.c

Contents are the same; this is just for recovery of PR #763.

Add: Tab-completion for AgensGraph syntax
